namePrefix: kustomize-

resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml
- ../base
- canary-rollout.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# patches:
#   - target:
#       kind: Deployment
#       name: guestbook-ui
#     patch: |
#       $patch: delete
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: DOES NOT MATTER