apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - canary/canary-service.yaml
# - canary/canary-ingress.yaml
- canary/preview-guestbook-ui.yaml
# - canary/canary-preview-ingress.yaml